source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MCImageLoader_Example', :exclusive => true do
  pod 'MCImageLoader', :path => '../'
end

target 'MCImageLoader_Tests', :exclusive => true do
  pod 'MCImageLoader', :path => '../'

  
end
